# Generated by Django 4.0.5 on 2022-06-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_rename_product_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_name',
            new_name='course_name',
        ),
    ]
