# Generated by Django 4.0.5 on 2022-06-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='grantedWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('grantedAt', models.DateTimeField(auto_now_add=True)),
                ('createBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granting', to='main.users')),
                ('likedBy', models.ManyToManyField(related_name='likes', to='main.users')),
            ],
        ),
    ]
